# Generated by Django 3.2.17 on 2024-04-03 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('cart', '0002_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('created_by', 'product')},
        ),
    ]
